title: Digital Accessibility Resources
description: Understand the importance of accessibility on Nashville.gov and help you make your site content fully accessible to visitors with needs of all kinds
theme: just-the-docs

url: https://metronashville.github.io/a11y-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
